name: Build and Publish

on:
  push:
    branches: [main]

permissions:
  id-token: write  # Required for OIDC
  contents: read

env:
  NODE_VERSION: '20'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for nbgv

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set version
        run: npm run setversion

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm run test:coverage

      - name: Build package
        run: npm run build:full

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 30

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: https://www.npmjs.com/package/@timheuer/vscode-ext-logger
    permissions:
      contents: write # Required for committing changelog and pushing tags
      id-token: write # Required for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for nbgv
          token: ${{ secrets.GITHUB_TOKEN }} # Use default token with contents: write permission

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Set version
        run: npm run setversion

      - name: Build package
        run: npm run build:full

      - name: Publish to NPM
        id: publish
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
